In [3]:
import pandas as pd
import sqlite3

con = sqlite3.connect('../cafef.db')

In [6]:
pd.read_sql("SELECT * from fireant_prices where date <= '2025-12-31' order by date", con)

,symbol,date,price_open,price_high,price_low,price_close,price_average,price_basic,adj_ratio,unit,...,sell_foreign_quantity,sell_foreign_value,current_foreign_room,buy_count,buy_quantity,sell_count,sell_quantity,prop_trading_net_deal_value,prop_trading_net_pt_value,prop_trading_net_value
0,VNINDEX,2009-01-02,312.49,313.34,312.18,313.34,313.340000,315.62,1.000000,1.0,...,428540.0,9.979840e+09,0.0,7688.0,14637140.0,6994.0,10868510.0,NaN,NaN,NaN
1,HNXINDEX,2009-01-02,105.26,106.10,104.47,104.47,104.470000,105.12,1.000000,1.0,...,54200.0,9.564000e+08,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2,TNG,2009-01-02,11.70,12.50,11.60,12.20,12.004027,11.80,19.458264,1000.0,...,0.0,0.000000e+00,2651000.0,29.0,40500.0,15.0,18900.0,NaN,NaN,NaN
3,L18,2009-01-02,11.00,11.00,11.00,11.00,11.000000,10.80,8.557175,1000.0,...,0.0,0.000000e+00,1707100.0,3.0,1100.0,10.0,5900.0,NaN,NaN,NaN
4,NTL,2009-01-02,33.70,33.80,33.40,33.80,33.800000,33.40,27.512133,1000.0,...,6540.0,2.210520e+08,5897480.0,55.0,55640.0,38.0,43970.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4787204,BHH,2025-12-31,17.60,17.60,17.60,17.60,17.600000,17.60,1.038889,1000.0,...,0.0,0.000000e+00,0.0,3.0,400.0,4.0,1100.0,0.0,0.0,0.0
4787205,DKG,2025-12-31,8.60,8.60,8.60,8.60,8.600000,8.60,1.000000,1000.0,...,0.0,0.000000e+00,7043650.0,0.0,0.0,1.0,200.0,0.0,0.0,0.0
4787206,VLS,2025-12-31,21.90,21.90,17.70,19.90,19.400000,20.80,1.000000,1000.0,...,0.0,0.000000e+00,0.0,64.0,26609.0,55.0,49402.0,0.0,0.0,0.0
4787207,TRV,2025-12-31,14.30,14.40,13.80,13.80,14.100000,14.30,1.000000,1000.0,...,0.0,0.000000e+00,-43625.0,76.0,38452.0,61.0,75556.0,0.0,0.0,0.0
4787208,HHB,2025-12-31,25.00,25.00,25.00,25.00,25.000000,25.00,1.041522,1000.0,...,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [11]:
price_df = pd.read_sql("SELECT symbol, count(*) as price_available_day from fireant_prices where date <= '2025-12-31' group by symbol", con)
price_df.set_index("symbol", inplace=True)
price_df

        price_available_day
symbol
A32                    1798
AAA                    3856
AAH                     492
AAM                    4062
AAT                    1195
...                     ...
YBC                    4224
YBM                    1842
YEG                    1882
YRC                    1234
YTC                    2105

[1819 rows x 1 columns]

In [12]:
financial_data_coverage_grid = pd.read_csv("../data/fireant_grid_sorted.csv")
financial_data_coverage_grid.rename({"Unnamed: 0": "symbol", "Unnamed: 0.1": "ID"}, axis=1, inplace=True)
financial_data_coverage_grid.set_index("symbol", inplace=True)
financial_data_coverage_grid

,ID,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,coverage_score
symbol,,,,,,,,,,,,,,,,,,,
TNG,1193,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,85.0
L18,637,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,85.0
NTL,801,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,85.0
NHC,775,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,85.0
DHA,287,5.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,84.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
GDC,1857,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
GMS,1858,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
HIS,1860,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ICA,1861,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
YAN,1889,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
financial_data_coverage_grid.join(price_df, on="symbol", how="left")

,ID,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,coverage_score,price_available_day
symbol,,,,,,,,,,,,,,,,,,,,
TNG,1193,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,85.0,4244.0
L18,637,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,85.0,4244.0
NTL,801,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,85.0,4242.0
NHC,775,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,85.0,4238.0
DHA,287,5.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,84.0,4242.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
GDC,1857,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
GMS,1858,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
HIS,1860,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
ICA,1861,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
YAN,1889,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN

In [14]:
import numpy as np
year_cols = [col for col in financial_data_coverage_grid.columns if col.isdigit()]
financial_data_coverage_grid['coverage_score_year'] = financial_data_coverage_grid[year_cols].clip(upper=3).sum(axis=1)/3
financial_data_coverage_grid

,ID,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,coverage_score,coverage_score_year
symbol,,,,,,,,,,,,,,,,,,,,
TNG,1193,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,85.0,17.0
L18,637,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,85.0,17.0
NTL,801,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,85.0,17.0
NHC,775,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,85.0,17.0
DHA,287,5.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,84.0,17.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
GDC,1857,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
GMS,1858,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
HIS,1860,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ICA,1861,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
YAN,1889,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [15]:
financial_data_coverage_grid = financial_data_coverage_grid.join(price_df, on="symbol", how="left")
financial_data_coverage_grid["price_available_day"] = financial_data_coverage_grid["price_available_day"].fillna(0)
financial_data_coverage_grid

,ID,2009,2010,2011,2012,2013,2014,2015,2016,2017,...,2019,2020,2021,2022,2023,2024,2025,coverage_score,coverage_score_year,price_available_day
symbol,,,,,,,,,,,,,,,,,,,,,
TNG,1193,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,85.0,17.0,4244.0
L18,637,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,85.0,17.0,4244.0
NTL,801,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,85.0,17.0,4242.0
NHC,775,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,85.0,17.0,4238.0
DHA,287,5.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,84.0,17.0,4242.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
GDC,1857,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
GMS,1858,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
HIS,1860,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ICA,1861,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
YAN,1889,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [17]:
financial_data_coverage_grid.query("~(coverage_score_year < 2 or price_available_day == 0)")

,ID,2009,2010,2011,2012,2013,2014,2015,2016,2017,...,2019,2020,2021,2022,2023,2024,2025,coverage_score,coverage_score_year,price_available_day
symbol,,,,,,,,,,,,,,,,,,,,,
TNG,1193,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,85.0,17.0,4244.0
L18,637,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,85.0,17.0,4244.0
NTL,801,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,85.0,17.0,4242.0
NHC,775,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,85.0,17.0,4238.0
DHA,287,5.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,84.0,17.0,4242.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DKG,301,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3.0,3.0,6.0,2.0,177.0
HTH,1607,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.0,3.0,0.0,0.0,0.0,0.0,6.0,2.0,320.0
VLS,1346,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3.0,3.0,6.0,2.0,13.0
TRV,1214,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3.0,3.0,6.0,2.0,138.0
HHB,488,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3.0,3.0,6.0,2.0,48.0

In [18]:
financial_data_coverage_grid.query("~(coverage_score_year < 2 or price_available_day == 0)").to_csv("../data/preprocessing_pipeline_results/simple_filter_fa_price.csv")

financial_data_coverage_grid.query("(coverage_score_year < 2 or price_available_day == 0)").to_csv("../data/preprocessing_pipeline_results/simple_filter_fa_price_holdout.csv")